name: "Close stale issues"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "Issue marked as stale due to inactivity. It will be closed in 5 days if no further activity occurs."
          close-issue-message: "This issue was closed because it was marked as stale and has not had recent activity. Please re-open if needed."
          stale-issue-label: "stale"
          exempt-issue-labels: "enhancement,bug"
          days-before-stale: 10
          days-before-close: 5
          days-before-pr-close: -1
